---
- name: Clean running node
  docker_container:
    name: 'phala-node'
    state: absent
  ignore_errors: yes

- name: Setup data path
  file:
    path: '/root/khala'
    state: directory

- name: Create a shared docker network
  docker_network:
    name: khala-node

- name: Spin up docker
  docker_compose:
    project_name: 'node'
    pull: yes
    definition:
        version: "3"
        services:
          node:
            image: phalanetwork/khala-node:latest
            container_name: phala-node
            hostname: phala-node
            ports:
            - "{{ vpn_ip if vpn_ip else "127.0.0.1" }}:9615:9615"
            - "{{ vpn_ip if vpn_ip else "127.0.0.1" }}:9616:9616"
            - "{{ vpn_ip if vpn_ip else "127.0.0.1" }}:9944:9944"
            - "{{ vpn_ip if vpn_ip else "127.0.0.1" }}:9945:9945"
            - "30333:30333"
            - "30334:30334"
            environment:
            - NODE_NAME={{ inventory_hostname }}
            - NODE_ROLE=MINER
            volumes:
            - /root/khala:/root/data
            restart: unless-stopped
        networks: 
          default: 
            external: 
              name: khala-node

- docker_container_info:
    name: phala-node
  register: output

- ansible.builtin.assert:
    that:
        - 'output.container.State.Status == "running"'
