# This playbook deploys a full khala mining pool
# You will need to register the pool and the workers afterward
---
- name: Basic setup
  hosts: worker
  become: yes
  roles:
    - basic-setup

# The next step will fail if you didn't run setup_vpn.yml first!

- name: Setup node
  hosts: node
  become: yes
  roles:
    - khala-node

- name: Setup prb
  hosts: prb
  become: yes
  roles:
    - khala-prb

- name: Setup worker
  hosts: worker
  become: yes
  roles:
    - setup-sgx
    - khala-worker
