# This playbook deploys a full khala mining pool
# You will need to register the pool and the workers afterward
---
- name: Setup node
  hosts: node
  become: yes
  roles:
    - basic-setup
    - khala-node

- name: Setup prb
  hosts: prb
  become: yes
  roles:
    - khala-node

- name: Setup worker
  hosts: worker
  become: yes
  roles:
    - basic-setup
    - setup-sgx
    - khala-worker
