---
- name: setup-node
  hosts: node
  become: yes
  roles:
  - basic-setup

- name: setup-pbr
  hosts: pbr
  become: yes
  roles:
  - basic-setup

- name: setup-worker
  hosts: worker
  become: yes
  roles:
  - basic-setup
  - setup-sgx